### ISSUE TITLE
indexページの作成:写真を並べる部分の作成

### ISSUE THREAD

**Issue by y-chan** [codeforjapan/StudyAtHome-LP#15]
PCなどの大画面では全体を、スマホなどの小さい画面では見切れるような表示を作りたいですが、index.vueに直書きすべきだと思うので、いったん保留です。

なお、どう実装すべきかわからないのでIssueで議論します。
![image](https://user-images.githubusercontent.com/34832037/84505312-7ef3df80-acf8-11ea-9908-7a9d05ef06e5.png)
![image](https://user-images.githubusercontent.com/34832037/84505377-9337dc80-acf8-11ea-923e-79084e56218f.png)

**Comment by kaizumaki** [comment]
こちらのissueやりますね。
