### ISSUE TITLE
indexページの作成:スクロールできるスクリーンショット一覧

### ISSUE THREAD

**Issue by y-chan** [codeforjapan/StudyAtHome-LP#16]
スクリーンショットの一覧のパスのリストを渡して、スクロール出来るように表示できるコンポーネントを作ってください。
![image](https://user-images.githubusercontent.com/34832037/84505894-7a7bf680-acf9-11ea-8cc6-63823a8bb651.png)
![image](https://user-images.githubusercontent.com/34832037/84505917-849df500-acf9-11ea-95bd-46dc27967676.png)

**Comment by kaizumaki** [comment]
こちらのissueやりますね。

**Comment by kaizumaki** [comment]
[Vuetifyのカルーセル](https://vuetifyjs.com/ja/components/carousels/)は使い勝手がよくなさそうなので（一画面ごとのスクロールしかできないっぽい）、[Vue Carousel](https://ssense.github.io/vue-carousel/)をインストールしてもいいですか？

**Comment by Nekoya3** [comment]
OKです！
