### ISSUE TITLE
indexページの作成:はじめるボタンの作成

### ISSUE THREAD

**Issue by y-chan** [codeforjapan/StudyAtHome-LP#17]
RoundButtonとは違い、影アリのフチなしなので、新しくボタンを作って対応してください。
![image](https://user-images.githubusercontent.com/34832037/84513035-d6e41380-ad03-11ea-929a-8b8d0cae3a9b.png)

**Comment by kota-yata** [comment]
着手したいんですが、「はじめる」はpropsにしますか？

**Comment by y-chan** [comment]
はい、そのようにしてください。
