### ISSUE TITLE
indexページの作成:背景色の青いラウンドボタンの作成

### ISSUE THREAD

**Issue by y-chan** [codeforjapan/StudyAtHome-LP#5]
以下のようなボタンを作れるコンポーネントを作成してください。
propsでボタンの内容(文字)とリンクを渡せるようにしてください。
![image](https://user-images.githubusercontent.com/34832037/83963974-9a1fb300-a8e4-11ea-97d7-a945c1f0cd99.png)
![image](https://user-images.githubusercontent.com/34832037/83964028-e1a63f00-a8e4-11ea-9e42-c8a4add81176.png)
ホバー時は`transition:0.3s;`と`opacity: 0.5;`で以下のように薄くなるようにしてください。
![image](https://user-images.githubusercontent.com/34832037/83964078-3d70c800-a8e5-11ea-9e89-4d3a52969958.png)

**Comment by kota-yata** [comment]
こちら着手したいのですがボタンの色やボタンサイズなどの指定はありますか？

**Comment by y-chan** [comment]
色ですが、`/assets/variables.scss`内に
```
// ==================
// color
$blue: #0071C2;
```
というコードを書いていただいて、ここで定義した`$blue`を使っていただければと思います。
その他フォントサイズ等に関しては[**こちらのFigma内**](https://www.figma.com/file/JBcf0nDLMqOyS5vffbZtvw/covid-edu?node-id=562%3A1983)を見ていただく方が速いと思います。

**Comment by kota-yata** [comment]
了解です
