### ISSUE TITLE
「生徒の利用する画面例」の部分が左寄りになっている

### ISSUE THREAD

**Issue by kota-yata** [codeforjapan/StudyAtHome-LP#57]
## スクリーンショット
![image](https://user-images.githubusercontent.com/51294895/84774969-86c5c380-b019-11ea-83e3-b074d9b8dea0.png)

**Comment by kaizumaki** [comment]
私が実装したとき、５枚以上の画像があることを前提としていたって言うのはありますね。ちょっと工夫しないといけないかもです。

**Comment by mamisada** [comment]
https://drive.google.com/drive/u/1/folders/1XaaO_uCPV84Wnckr6iO6gjD4UG0yltJZ
画像を新しくして追加したので、５枚に変えたいです！

**Comment by MaySoMusician** [comment]
Duplicate of #75
