### ISSUE TITLE
screenshots/生徒の利用する画面例(画面の更新)

### ISSUE THREAD

**Issue by mamisada** [codeforjapan/StudyAtHome-LP#75]
左によってしまう問題を解消するために画像を差し替えて、増やしておきたい。ので
４枚にしました！

トップ画面（入力付き）
![Screen Shot 2020-07-18 at 16 33 11](https://user-images.githubusercontent.com/2863745/87847634-c4698500-c914-11ea-8e8f-5e8cdea8a590.png)
時間割
![Screen Shot 2020-07-18 at 16 31 56](https://user-images.githubusercontent.com/2863745/87847639-d4816480-c914-11ea-814e-5d090346ebb4.png)
内容
![Screen Shot 2020-07-18 at 16 39 39](https://user-images.githubusercontent.com/2863745/87847734-4c4f8f00-c915-11ea-9135-b6e88bf4b615.png)
カレンダー
![Screen Shot 2020-07-18 at 16 33 44](https://user-images.githubusercontent.com/2863745/87847631-c16e9480-c914-11ea-8795-f6c63eddd88f.png)

**Comment by kaizumaki** [comment]
対応しますね。
