### ISSUE TITLE
indexページの作成:コントリビュータのアイコンと名前、役割の表示

### ISSUE THREAD

**Issue by y-chan** [codeforjapan/StudyAtHome-LP#9]
以下のようなものを、コントリビュータのアイコンのパス、名前、役割をpropsで渡すことで表示できるコンポーネントを作ってください。
![image](https://user-images.githubusercontent.com/34832037/84180577-b5481980-aac2-11ea-9804-0d0d60691750.png)
なお、詳しいデザインは[**Figma**](https://www.figma.com/file/JBcf0nDLMqOyS5vffbZtvw/covid-edu?node-id=562%3A1983)をご覧ください

**Comment by kota-yata** [comment]
着手します
